#!/usr/bin/env python3
"""make-harness.py <Compiler++ root> <out dir> [case ...]
   make-harness.py <Compiler++ root> <out dir> --workload <dir> --rounds <n> [--input]

Writes <out dir>/harness.cpp: the whole of Compiler++ as one translation unit,
regenerated from its current sources by its own dist/amalgamate.py (run on a
scratch copy, so the Compiler++ tree is not touched), with -DCOMPILERPP_NO_MAIN's
guard defined, and a main() that compiles each named test case in memory, runs it
on Compiler++'s VM and prints what it printed. The cases and their stdin are
compiled in as strings: a program on the C6747 simulator has no files and no argv.

With no cases named, every case that has a tests/expected_run/<case>.txt and reads no
stdin (tests/input/<case>.txt): nothing is redirected, because cpp11's <iostream> has
no std::streambuf - the program's output and the diagnostics go straight out.
Each case prints as
    === <case>
    <its stdout>
    [runtime error: <message>]
    main returned <n>        (or: compile failed, and the diagnostics)
and the last line is "cases <n>". The reference is the same harness built by clang.

With --workload, the harness is the timed one instead: every .cpp in <dir> is compiled
<n> times over and nothing is run - what is measured is Compiler++ compiling. Each file
prints its fingerprint - functions, instructions and a 32-bit checksum of the bytecode -
which every build of Compiler++ must agree on, and the last line is "rounds <n> files <m>".

With --input as well, no source is compiled in: main takes the file's path from argv[1]
and reads it the way Compiler++'s own main does - an ifstream, `ss << in.rdbuf()` - and
argv[2], if given, is the number of rounds (0 reads the file and compiles nothing, which is
how the cost of the read is measured apart from the compile). The C6747 simulator does hand
a program argv (the image linked with --args=N and loaded by DSS's loadProgram(file, args))
and serves fopen from the host's files through CIO: measured 2026-09-30, both TI toolchains.
The line printed is the same, the name being the path's basename without its .cpp.
"""
import os
import shutil
import subprocess
import sys
import tempfile


def c_string(text):
    out = []
    for ch in text:
        o = ord(ch)
        if ch == '\\': out.append('\\\\')
        elif ch == '"': out.append('\\"')
        elif ch == '\n': out.append('\\n"\n"')
        elif ch == '\t': out.append('\\t')
        elif ch == '?': out.append('\\?')          # no trigraphs
        elif 32 <= o < 127: out.append(ch)
        else: out.append('\\%03o' % (o & 0xFF))
    return '"' + ''.join(out) + '"'


def amalgamate(root):
    with tempfile.TemporaryDirectory() as tmp:
        shutil.copytree(os.path.join(root, 'Compiler++'), os.path.join(tmp, 'Compiler++'))
        os.makedirs(os.path.join(tmp, 'dist'))
        shutil.copy(os.path.join(root, 'dist', 'amalgamate.py'), os.path.join(tmp, 'dist'))
        subprocess.check_call([sys.executable, os.path.join('dist', 'amalgamate.py')], cwd=tmp,
                              stdout=subprocess.DEVNULL)
        return open(os.path.join(tmp, 'dist', 'compilerpp_amalgamated.cpp')).read()


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    root, outdir, names = sys.argv[1], sys.argv[2], sys.argv[3:]
    workload, rounds, byInput = None, 1, False
    if '--input' in names:
        names.remove('--input'); byInput = True
    if '--workload' in names:
        i = names.index('--workload'); workload = names[i + 1]; del names[i:i + 2]
    if '--rounds' in names:
        i = names.index('--rounds'); rounds = int(names[i + 1]); del names[i:i + 2]
    tests = os.path.join(root, 'tests')
    if workload:
        names = sorted(f[:-4] for f in os.listdir(workload) if f.endswith('.cpp') and ' ' not in f)
    elif not names:
        names = sorted(f[:-4] for f in os.listdir(os.path.join(tests, 'expected_run'))
                       if f.endswith('.txt') and ' ' not in f
                       and not os.path.exists(os.path.join(tests, 'input', f)))
    os.makedirs(outdir, exist_ok=True)
    open(os.path.join(outdir, 'compilerpp_amalgamated.cpp'), 'w').write(amalgamate(root))

    cases = []
    for n in names:
        src = open(os.path.join(workload or os.path.join(tests, 'cases'), n + '.cpp')).read()
        cases.append((n, '' if byInput else src))

    h = []
    h.append('// Generated by tools/c6747/compilerpp/make-harness.py - do not edit.')
    h.append('#define COMPILERPP_NO_MAIN 1')
    if workload:
        h.append('#define HARNESS_ROUNDS %d' % rounds)
    if byInput:
        h.append('#define HARNESS_INPUT 1')
    h.append('#include "compilerpp_amalgamated.cpp"')
    h.append('namespace {')
    h.append('struct Case { const char *name; const char *source; };')
    h.append('const Case cases[] = {')
    for n, src in cases:
        h.append('{ %s,\n%s },' % (c_string(n), c_string(src)))
    h.append('};')
    h.append(r'''
// What main.cpp does, minus the command line: the steps tests/embed_smoke.cpp uses.
bool compileToImage(const std::string &sourceText, Image &image) {
    std::string source = sourceText;
    Diagnostics diag("embedded");
    int preludeLines = 0;
    const std::string prelude = preludeFor(source, preludeLines);
    if (!prelude.empty()) { source = prelude + source; diag.setLineOffset(preludeLines); }
    source = expandDefines(source, diag);
    bool built = false;
    {
        cxx::Parser parser(source, diag);
        std::vector<cc::Decl*> unit = parser.parseTranslationUnit();
        {
            SemanticAnalyzer sem(diag);
            sem.analyze(unit);
            Layout layout(diag);
            layout.computeAll(sem.classMap());
            if (!diag.hadError()) {
                IRModule module;
                {
                    cxx::Lowering lower(module, layout, diag, sem.classMap());
                    lower.lowerClasses();
                    lower.lowerUnit(unit);
                }
                if (!diag.hadError()) {
                    CodeGen gen(diag);
                    gen.generate(module, image);
                    built = !diag.hadError();
                }
            }
            for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
            unit.clear();
        }
    }
    return built;
}
} // namespace

#ifdef HARNESS_ROUNDS
// The timed harness: compile every file harnessRounds times, run nothing.
int harnessRounds = HARNESS_ROUNDS;
// One file only, or -1 for all: runca.js writes it after the load has run to main,
// past the start-up code that initialised it, so each file can be its own run.
int harnessFile = -1;
unsigned fingerprint(const Image &image, unsigned &instructions) {
    unsigned h = 2166136261u;
    instructions = 0;
    for (std::size_t f = 0; f < image.functions.size(); ++f) {
        const FuncImage &fn = image.functions[f];
        for (std::size_t c = 0; c < fn.name.size(); ++c) h = (h ^ (unsigned char)fn.name[c]) * 16777619u;
        for (std::size_t i = 0; i < fn.code.size(); ++i) {
            const Instr &in = fn.code[i];
            h = (h ^ (unsigned)in.op) * 16777619u;
            h = (h ^ (unsigned)in.imm) * 16777619u;
            h = (h ^ (unsigned)in.b) * 16777619u;
            ++instructions;
        }
    }
    return h;
}

// One file compiled harnessRounds times over; what is printed is what every build must agree on.
void timeOne(const char *name, const std::string &source) {
    unsigned h = 0, instructions = 0, functions = 0;
    bool built = true;
    for (int r = 0; r < harnessRounds; ++r) {
        Image image;
        built = compileToImage(source, image);
        h = fingerprint(image, instructions);
        functions = (unsigned)image.functions.size();
    }
    std::cout << name << " " << (built ? "ok" : "FAILED") << " functions " << functions
              << " instructions " << instructions << " fingerprint " << h << std::endl;
}
#ifdef HARNESS_INPUT
// Compiler++'s own readFile: the input arrives through the C library, as it does natively.
bool readFile(const std::string &path, std::string &out) {
    std::ifstream in(path.c_str());
    if (!in) return false;
    std::ostringstream ss;
    ss << in.rdbuf();
    out = ss.str();
    return true;
}
int main(int argc, char **argv) {
    if (argc < 2) { std::cout << "usage: harness <file.cpp> [rounds]" << std::endl; return 2; }
    if (argc > 2) harnessRounds = std::atoi(argv[2]);
    std::string path = argv[1], source;
    if (!readFile(path, source)) { std::cout << "cannot open " << path << std::endl; return 2; }
    std::string::size_type slash = path.find_last_of("/\\");
    std::string name = slash == std::string::npos ? path : path.substr(slash + 1);
    if (name.size() > 4 && name.substr(name.size() - 4) == ".cpp") name = name.substr(0, name.size() - 4);
    std::cout << "read " << source.size() << " bytes" << std::endl;
    timeOne(name.c_str(), source);
    std::cout << "rounds " << harnessRounds << " files " << 1 << std::endl;
    return 0;
}
#else
int main() {
    const int n = (int)(sizeof cases / sizeof cases[0]);
    for (int i = 0; i < n; ++i) {
        if (harnessFile >= 0 && i != harnessFile) continue;
        timeOne(cases[i].name, cases[i].source);
    }
    std::cout << "rounds " << harnessRounds << " files " << n << std::endl;
    return 0;
}
#endif
#else
int main() {
    const int n = (int)(sizeof cases / sizeof cases[0]);
    for (int i = 0; i < n; ++i) {
        std::cout << "=== " << cases[i].name << std::endl;
        Image image;
        if (!compileToImage(cases[i].source, image)) {
            std::cout << "compile failed" << std::endl;
            continue;
        }
        VM vm;
        bool ok = false;
        const vmword result = vm.run(image, ok);
        std::cout.flush();
        if (!ok) std::cout << "runtime error: " << vm.errorMessage() << std::endl;
        else std::cout << "main returned " << (long)result << std::endl;
    }
    std::cout << "cases " << n << std::endl;
    return 0;
}
#endif''')
    open(os.path.join(outdir, 'harness.cpp'), 'w').write('\n'.join(h) + '\n')
    print('%s: %d cases' % (os.path.join(outdir, 'harness.cpp'), len(cases)))


if __name__ == '__main__':
    main()
